### ISSUE TITLE
chokes on Clojure 1.7.0

### ISSUE THREAD

**Issue by laforge49** [gdeer81/marginalia#158]
Had to downgrade to 1.6.0. 

Here is the line causing the problem when using Clojure 1.7.0:

(def ^:dynamic _context-atom_
  "Holds the operational context of the agent being operated on."
  nil)

C:\Users\Bill\Documents\GitHub\agent2>lein marg
Generating Marginalia documentation for the following source files:
   C:\Users\Bill\Documents\GitHub\agent2\src\agent2\core.clj

Exception in thread "main" java.lang.RuntimeException: Problem parsing near line
 3 <dynamic *context-atom*> original reported cause is clojure.lang.ArityExcepti
on: Wrong number of args (4) passed to: parser/read-keyword -- clojure.lang.Arit
yException: Wrong number of args (4) passed to: parser/read-keyword, compiling:(
C:\Users\Bill\AppData\Local\Temp\form-init4303374623502166225.clj:1:107)
        at clojure.lang.Compiler.load(Compiler.java:7239)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Problem parsing near line 3 <dynamic *con
text-atom*> original reported cause is clojure.lang.ArityException: Wrong number
 of args (4) passed to: parser/read-keyword -- clojure.lang.ArityException: Wron
g number of args (4) passed to: parser/read-keyword
        at clojure.lang.LispReader.read(LispReader.java:292)
        at clojure.lang.LispReader.read(LispReader.java:196)
        at clojure.lang.LispReader.read(LispReader.java:190)
        at marginalia.parser$parse_STAR_$fn__418$fn__421.invoke(parser.clj:153)
        at marginalia.parser$parse_STAR_$fn__418.invoke(parser.clj:152)
        at clojure.core$repeatedly$fn__5111.invoke(core.clj:4921)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$map$fn__4553.invoke(core.clj:2616)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.boundedLength(RT.java:1735)
        at clojure.lang.RestFn.applyTo(RestFn.java:130)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$mapcat.doInvoke(core.clj:2660)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at clojure.core$tree_seq$walk__5045$fn__5046.invoke(core.clj:4739)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.LazySeq.more(LazySeq.java:85)
        at clojure.lang.RT.more(RT.java:683)
        at clojure.core$rest__4114.invoke(core.clj:73)
        at clojure.core$flatten.invoke(core.clj:6851)
        at marginalia.parser$parse_STAR_.invoke(parser.clj:146)
        at marginalia.parser$parse.invoke(parser.clj:382)
        at marginalia.parser$parse_file.invoke(parser.clj:400)
        at marginalia.core$path_to_doc.invoke(core.clj:177)
        at clojure.core$map$fn__4553.invoke(core.clj:2624)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$map$fn__4553.invoke(core.clj:2616)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$map$fn__4553.invoke(core.clj:2616)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$apply.invoke(core.clj:630)
        at marginalia.hiccup$eval57$fn__58.invoke(hiccup.clj:99)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at clojure.lang.Var.invoke(Var.java:379)
        at marginalia.html$toc_html.invoke(html.clj:189)
        at marginalia.html$uberdoc_html.invoke(html.clj:400)
        at marginalia.core$uberdoc_BANG_.invoke(core.clj:208)
        at marginalia.core$run_marginalia.doInvoke(core.clj:293)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at user$eval786.invoke(form-init4303374623502166225.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        ... 11 more
Subprocess failed
C:\Users\Bill\Documents\GitHub\agent2>

**Comment by rasmuserik** [comment]
I also had problems with marginalia on Clojure 1.7.0, but solved it by using https://clojars.org/michaelblume/marginalia as mentioned in #153

**Comment by eigenhombre** [comment]
@gdeer81 There is some work needed on Marginalia, in particular this issue and #153 ... are you open to someone else taking on maintenance of this project?  CC @fogus

**Comment by fgiasson** [comment]
@eigenhombre +1

I don't think Marginalia should die or be forked in many different places. It is a great, neat and necessary documentation tool.

**Comment by fogus** [comment]
I've not been involved with Marginalia for a couple of years now, but I have no problem with someone else taking the reigns.  As long as @gdeer81 takes the necessary steps to facilitate the transfer that is.

**Comment by eigenhombre** [comment]
@MichaelBlume What do you think? I'm already using your fork by default. @gdeer81 are you willing to facilitate transfer? I know another developer who just got bitten by this as well.

**Comment by n2o** [comment]
I have the same issue with clojurescript "1.7.228" and marginalia 0.8.0... Thanks for your help

**Comment by gdeer81** [comment]
Is this still an issue with version 9?

**Comment by MichaelBlume** [comment]
I'm pretty sure this has been fixed
