### ISSUE TITLE
lein marg fails under clojure 1.9.*

### ISSUE THREAD

**Issue by aaelony** [gdeer81/marginalia#167]
Works fine under clojure 1.8.0 but when I change my project code to anything 1.9, e.g. [org.clojure/clojure "1.9.0-beta4"] I get the following error message:

```
Exception in thread "main" java.lang.RuntimeException: Problem parsing near line 1 < [taoensso.timbre :refer [info warn error] :as timbre]> original reported cause is java.lang.NoSuchMethodException: clojure.lang.LispReader.matchSymbol(java.lang.String) -- java.lang.NoSuchMethodException: clojure.lang.LispReader.matchSymbol(java.lang.String), compiling:(/private/var/folders/hj/ym9mtk0j06d8c9wnwsfl2wxh27tj6l/T/form-init3751602114729095244.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Problem parsing near line 1 < [taoensso.timbre :refer [info warn error] :as timbre]> original reported cause is java.lang.NoSuchMethodException: clojure.lang.LispReader.matchSymbol(java.lang.String) -- java.lang.NoSuchMethodException: clojure.lang.LispReader.matchSymbol(java.lang.String)
	at clojure.lang.LispReader.read(LispReader.java:304)
	at clojure.lang.LispReader.read(LispReader.java:206)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at marginalia.parser$parse_STAR_$fn__671$fn__674.invoke(parser.clj:160)
	at marginalia.parser$parse_STAR_$fn__671.invoke(parser.clj:159)
	at clojure.core$repeatedly$fn__6178.invoke(core.clj:5094)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5125.invokeStatic(core.clj:137)
	at clojure.core$seq__5125.invoke(core.clj:137)
	at clojure.core$tree_seq$walk__6102$fn__6103.invoke(core.clj:4890)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.LazySeq.more(LazySeq.java:85)
	at clojure.lang.RT.more(RT.java:715)
	at clojure.core$rest__5111.invokeStatic(core.clj:73)
	at clojure.core$flatten.invokeStatic(core.clj:7061)
	at clojure.core$flatten.invoke(core.clj:7061)
	at marginalia.parser$parse_STAR_.invokeStatic(parser.clj:153)
	at marginalia.parser$parse_STAR_.invoke(parser.clj:150)
	at marginalia.parser$parse.invokeStatic(parser.clj:389)
	at marginalia.parser$parse.invoke(parser.clj:380)
	at marginalia.parser$parse_file.invokeStatic(parser.clj:418)
	at marginalia.parser$parse_file.invoke(parser.clj:415)
	at marginalia.core$path_to_doc.invokeStatic(core.clj:177)
	at marginalia.core$path_to_doc.invoke(core.clj:175)
	at clojure.core$map$fn__5589.invoke(core.clj:2750)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5125.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5589.invoke(core.clj:2743)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5125.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5589.invoke(core.clj:2743)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5125.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$apply.invoke(core.clj:652)
	at marginalia.hiccup$eval213$fn__214.invoke(hiccup.clj:99)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.lang.Var.invoke(Var.java:381)
	at marginalia.html$toc_html.invokeStatic(html.clj:198)
	at marginalia.html$toc_html.invoke(html.clj:197)
	at marginalia.html$uberdoc_html.invokeStatic(html.clj:409)
	at marginalia.html$uberdoc_html.invoke(html.clj:401)
	at marginalia.core$uberdoc_BANG_.invokeStatic(core.clj:206)
	at marginalia.core$uberdoc_BANG_.invoke(core.clj:196)
	at marginalia.core$run_marginalia.invokeStatic(core.clj:311)
	at marginalia.core$run_marginalia.doInvoke(core.clj:248)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at user$eval1201.invokeStatic(form-init3751602114729095244.clj:1)
	at user$eval1201.invoke(form-init3751602114729095244.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
Subprocess failed
```

There are no other problems under clojure 1.9.* in my codebase if I don't use marginalia.

Cheers,
Avram

**Comment by seancorfield** [comment]
`clojure.lang.LispReader/matchSymbol` now requires two arguments in Clojure 1.9: a `String` and a `Resolver` (which looks like it can be `nil`?).

**Comment by benjamin-bader** [comment]
Would either of you care to glance at PR #168, which addresses this issue?  I've been away from Clojure for quite some time now, so maybe I'm missing something.

**Comment by seancorfield** [comment]
That's an interesting -- and pretty elegant-looking solution -- to the problem. I didn't realize there was a new Var introduced around this, but I hadn't dug very far. Given that 1.9 has reached RC1 with no further changes planned, it would be nice to have Marginalia working with it by the time it goes "gold". Thanks @benjamin-bader !

**Comment by benjamin-bader** [comment]
Cool, thanks for checking!  I appreciate the time spent.  I'm able to land the PR myself, but it will be up to @gdeer81 to make a proper release with full support for 1.9.

**Comment by benjamin-bader** [comment]
Fixed with #168.

**Comment by aaelony** [comment]
This is great! Do we need a version bump and release to clojars?

**Comment by gdeer81** [comment]
Sounds like a good idea.  release party tonight!

On Nov 8, 2017 11:36 AM, "aaelony" <notifications@github.com> wrote:

This is great! Do we need a version bump and release to clojars?




> On Nov 7, 2017, at 10:10 PM, Ben Bader <notifications@github.com> wrote:
>
> Closed #167.
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gdeer81/marginalia/issues/167#issuecomment-342894855>,
or mute the thread

**Comment by aaelony** [comment]
super! woo hoo!!

**Comment by seancorfield** [comment]
Thanks @gdeer81 -- I'm breaking ground on a new project today and want to try Marginalia as documentation for it (so I expect to write and publish a Boot task to drive Marginalia). It'll be Clojure 1.9 of course :)

**Comment by aaelony** [comment]
awesome! I think Sean Corfield uses Boot heavily so run it by him as well.
I typically use both marginalia and codox. Great stuff!

**Comment by aaelony** [comment]
oops! misread this on my phone, but you guys probably understood what I misread ;)
